### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by nuass** [xuanzebi/BERT-NER#1]
你好。
在训练刚开始报错，训练数据是tmp里的数据。
File "run_NER.py", line 505, in convert_single_example
    assert len(label_id) == max_seq_length
AssertionError
len(label_id)的长度比max_seq_length小1，但是有的差的比较多。
![image](https://user-images.githubusercontent.com/22679115/59400453-0d721000-8dca-11e9-85c6-4e108b184a37.png)

**Comment by xuanzebi** [comment]
这个是我刚开始用bert写的...写的估计有点问题,, 你可以把那几行代码重新修改一下，label_id和input_id对应上就行..少1 应该是我最后label_id没有加 SEP。

**Comment by xuanzebi** [comment]
数据有一些有问题
比如 输入句子 叩 问 澳 门 =- =- =- 贺 澳 门 回 归 进 入 倒 计 时 ，label :O O B-LOC I-LOC O O O O B-LOC I-LOC O O O O O O O
text = tokenization.convert_to_unicode(line[0])会把输入的=- 处理成两个字符，所以会导致label对应不上，需要手动处理一下。
然后label_id少一个 是没有加SEP  已修改
