### ISSUE TITLE
Assertion label_id==max_seq_length报错

### ISSUE THREAD

**Issue by cy001457** [xuanzebi/BERT-NER#2]
在输出完实验结果后，打印的label显示50 36 少了14个label
报错是 assert_len(label_id) == max_seq_length
请问如何解决谢谢。

**Comment by xuanzebi** [comment]
bert tokenizer在处理字符的时候，会将一些特殊符号处理掉，比如word是-=，然后就被处理掉了，所以建议自己在代码中手动改一下这部分，当然你也可以将少的那部分word打印出来，然后从原始数据中删除也可以。
