### ISSUE TITLE
运行环境问题

### ISSUE THREAD

**Issue by JensonXIE** [xuanzebi/BERT-NER#4]
老哥，你的电脑配置是多少？我不管用win还是ubuntu跑你的代码（run_NER.py）、卡死以后就报错了。！16G的内存

**Comment by xuanzebi** [comment]
跑的哪个数据  我用服务器跑的  
BERT 这种预训练模型本来就很耗显存吃配置.

个人建议可以试试google colab 或者kaggle 的kernel跑跑  免费gpu。

**Comment by JensonXIE** [comment]
@xuanzebi 感谢
