### ISSUE TITLE
预测结果

### ISSUE THREAD

**Issue by JensonXIE** [xuanzebi/BERT-NER#5]
run_NER.py文件执行
训练后：
--task_name=NER  --do_train=true  --do_eval=false  --do_predict=false  --data_dir=C:\Users\xiezx\Desktop\临时\BERT-CH-NER-master\tmp\  --vocab_file=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\vocab.txt  --bert_config_file=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\bert_config.json  --init_checkpoint=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\bert_model.ckpt  --max_seq_length=256 --train_batch_size=16 --learning_rate=2e-5  --num_train_epochs=3.0  --output_dir=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\output\

进行预测：
--task_name=NER  --do_train=false  --do_eval=false  --do_predict=true  --data_dir=C:\Users\xiezx\Desktop\临时\BERT-CH-NER-master\tmp\  --vocab_file=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\vocab.txt  --bert_config_file=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\bert_config.json  --init_checkpoint=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\bert_model.ckpt  --max_seq_length=256 --train_batch_size=16 --learning_rate=2e-5  --num_train_epochs=3.0  --output_dir=C:\Users\xiezx\Desktop\souhu\data\chinese_L-12_H-768_A-12\output\

生成的文件test_prediction.txt内容貌似有问题吧？？？（前5行）
[CLS] [CLS] O [CLS] B-PER O [CLS] O O O I-LOC O O [CLS] I-ORG B-ORG I-ORG [CLS] [CLS] I-ORG [CLS] [CLS] B-PER [CLS] [CLS] I-LOC [CLS] I-ORG [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-LOC I-ORG [CLS] I-LOC I-LOC I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-LOC I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-LOC [CLS] [CLS] I-LOC I-LOC I-LOC [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-LOC I-LOC I-LOC [CLS] I-LOC [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-LOC [CLS] I-LOC I-LOC I-ORG I-ORG [CLS] [CLS]
I-LOC [CLS] I-PER O I-ORG B-PER B-PER O O I-ORG I-ORG I-ORG I-PER I-PER O I-LOC O O O O [CLS] O [CLS] O O O B-LOC I-LOC I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] I-ORG I-ORG I-LOC I-LOC I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-LOC I-LOC [CLS] I-LOC [CLS] I-LOC [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-LOC I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-LOC I-LOC [CLS] I-LOC I-LOC I-LOC I-LOC [CLS] [CLS] I-ORG [CLS] [CLS] I-ORG I-LOC I-ORG I-ORG I-ORG B-PER [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG B-PER [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] B-PER I-ORG I-LOC I-LOC I-LOC I-LOC I-LOC I-LOC I-LOC [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-LOC I-ORG I-LOC I-LOC I-LOC I-ORG [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] I-ORG I-ORG B-PER I-ORG I-ORG I-ORG I-LOC I-ORG I-LOC [CLS] [CLS] [CLS] I-LOC I-LOC I-LOC I-LOC I-LOC [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER B-PER [CLS] B-PER I-LOC B-PER [CLS] B-PER I-LOC I-LOC I-LOC I-LOC I-LOC [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG
[CLS] [CLS] [CLS] B-PER I-PER I-ORG O I-ORG B-ORG I-ORG [CLS] [CLS] O [CLS] O [CLS] [CLS] [CLS] [CLS] B-PER [CLS] [CLS] B-ORG [CLS] [CLS] B-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG [CLS] [CLS]
[CLS] [CLS] I-LOC I-ORG I-ORG B-LOC [CLS] B-ORG [CLS] I-LOC B-LOC [CLS] [CLS] I-PER [CLS] [CLS] O I-ORG I-ORG B-ORG O O [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER B-PER [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] I-ORG B-PER I-ORG B-PER [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER B-PER B-PER [CLS] B-PER B-PER [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS]
I-LOC [CLS] B-PER B-PER [CLS] O O B-ORG [CLS] O O O O O B-ORG O [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] I-ORG B-PER [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER B-PER I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] B-PER I-ORG I-ORG I-ORG I-ORG I-ORG I-ORG [CLS] [CLS] I-ORG [CLS] I-ORG I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG I-ORG [CLS] I-ORG I-ORG [CLS] I-ORG [CLS] [CLS] I-ORG [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS] I-ORG B-PER [CLS] I-ORG [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] [CLS] I-ORG [CLS]

**Comment by xuanzebi** [comment]
我刚刚 重新跑了一遍 我这边没问题哈，你可以用我最近更新的代码再跑一遍试试
![image](https://user-images.githubusercontent.com/26642184/69067721-90288680-0a5e-11ea-9552-fac7aef68746.png)
如果你那边还有问题的话，可以本地debug 试试呢

**Comment by JensonXIE** [comment]
@xuanzebi 非常感谢耐心解答，已经在colab上使用GPU跑通训练结果

**Comment by CherylQi** [comment]
> @xuanzebi 非常感谢耐心解答，已经在colab上使用GPU跑通训练结果

你好，想问下为什么我在colab上显示没用GPU？配置改了GPU但一直在CPU上跑，最后自动停了
