### ISSUE TITLE
coreEntityEmotion_train.txt数据集还有吗？

### ISSUE THREAD

**Issue by hungita** [xuanzebi/BERT-NER#7]
有的话，发我邮箱893214549@qq.com，谢谢。

**Comment by xuanzebi** [comment]
data.zip https://pan.baidu.com/s/1j5jcMlww-G7RYH2uZhLLHw  提取码：6i6q 
sample_submission_stage2.txt  https://pan.baidu.com/s/1h7us_vEhvq2qO5d61ozniA   提取码：3d52 
coreEntityEmotion_test_stage2.zip  https://pan.baidu.com/s/1k9mCxTMYr9nH8bTHzrLryg  提取码：c3bg

**Comment by hungita** [comment]
谢谢。
