### ISSUE TITLE
分词后的 tag问题

### ISSUE THREAD

**Issue by Crescentz** [xuanzebi/BERT-NER#8]
Person  原来是 B-PER  分词后是 Per ##son 那么他的tag应该是什么
这个哪里有说明么

**Comment by xuanzebi** [comment]
bert 因为采用了wordpiece 所以在分英文词的时候会分成这样
这个时候就需要手动处理了，或者刚开始就用第一部分token代替这个词，
或者参考bert论文中的处理方法。
