### ISSUE TITLE
请问为什么eval时会报错？

### ISSUE THREAD

**Issue by jma-code** [xuanzebi/BERT-NER#9]
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Shapes of all inputs must match: values[0].shape = [512] != values[1].shape = [10]
	 [[node confusion_matrix_1/stack_1 (defined at /tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[ConstantFoldingCtrl/confusion_matrix_2/assert_less/Assert/AssertGuard/Switch_0/_1364]]
  (1) Invalid argument: Shapes of all inputs must match: values[0].shape = [512] != values[1].shape = [10]
	 [[node confusion_matrix_1/stack_1 (defined at /tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by pomeloking01** [comment]
def metric_fn(label_ids, pred_ids)这个函数中数字8改成 你labels的长度
